version: '3.9'

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0.3-ubuntu2204
    container_name: mongodb-container
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - ddh-mongo:/data/db

networks:
  postgres:
    driver: bridge

volumes:
  ddh-postgres:
  ddh-mongo:
